# Generated by Django 3.0.7 on 2021-02-11 15:56

import catmaid.fields
from django.conf import settings
import django.contrib.postgres.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catmaid', '0108_fix_deep_link_model_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaintLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', catmaid.fields.DbDefaultDateTimeField(default=django.contrib.postgres.functions.TransactionNow)),
                ('edition_time', catmaid.fields.DbDefaultDateTimeField(default=django.contrib.postgres.functions.TransactionNow)),
                ('location_x', models.FloatField()),
                ('location_y', models.FloatField()),
                ('location_z', models.FloatField()),
                ('label_id', models.IntegerField()),
                ('needs_edit', models.BooleanField()),
                ('to_delete', models.BooleanField()),
                ('comment', models.TextField()),
                ('name', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catmaid.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'paint_label',
            },
        ),
    ]
